plugins:
  - 'eslint-plugin-tsdoc'
extends: './node_modules/@seek/seek-module-toolkit/config/.eslintrc.yml'
rules:
  tsdoc/syntax:
    - error
overrides:
  - files: '**/*.test.ts'
    rules:
      # This triggers on e.g. expect(mockCtx.set).toBeCalledWith
      '@typescript-eslint/unbound-method':
        - off
